title: Bangla Basics
description: Learn Bengali online for free!
date_format: "%b %-d, %Y"
header_pages:
  - index.md
  - about.md
  - lessons.md
  - cheat-sheets.md
  - resources.md
permalink: pretty
theme: minima
