title: Bengali Grammar Basics
description: An introduction to the grammar of the Bengali language
date_format: "%b %-d, %Y"
author: Shaandro Sarkar
email: shaandrosarkar@gmail.com
minima:
  social_links:
    twitter: ssshaiwala
    github: shaandro
    linkedin: shaandro
theme: minima
